Third homework
Verkqis/Homework pull request #4
Opened 2023-05-19 14:56 UTC by Verkqis

Ir!

2023-06-12 12:50 UTC, janistumpelis requested changes
Tas esošais kods ir ok, bet nepabeigtie uzdevumi ir jāpabeidz.

2023-06-12 12:50 UTC, janistumpelis commented on src/main/java/io/codelex/classesandobjects/practice/Account.java
> +    public static void main(String[] args) {
Iekš klases no kuras veidojam objektus mēs main metodi iekšā neliec, iznes ārā citā klasē.

2023-06-12 12:50 UTC, janistumpelis commented on src/main/java/io/codelex/classesandobjects/practice/BankAccount.java
> +    public static void main(String[] args) {
Tas pats - iznes main metodi ārā citā klasē.

2023-06-12 12:50 UTC, janistumpelis commented on src/main/java/io/codelex/classesandobjects/practice/savingsaccount/SavingsAccountTest.java
> +        SavingsAccount JohnDoe = new SavingsAccount(input);
Mainīgo vajadzētu ar mazo burtu, savādāk liekas, ka šeit, piemēram, tiek saukta statiska metode no klases nevis parasta no objekta - `JohnDoe.setAnnualInterest(input);`

2023-06-12 15:50 UTC, Verkqis commented
Ok izdarīšu

pirmd., 2023. g. 12. jūn., plkst. 15:50 — lietotājs janistumpelis (<
***@***.***>) rakstīja:

> ***@***.**** requested changes on this pull request.
>
> Tas esošais kods ir ok, bet nepabeigtie uzdevumi ir jāpabeidz.
> ------------------------------
>
> In src/main/java/io/codelex/classesandobjects/practice/Account.java
> <https://github.com/Verkqis/Homework/pull/4#discussion_r1226616111>:
>
> >      @Override
>      public String toString() {
>          return owner + " balance: " + balance;
>      }
> +
> +    public static void main(String[] args) {
>
> Iekš klases no kuras veidojam objektus mēs main metodi iekšā neliec, iznes
> ārā citā klasē.
> ------------------------------
>
> In src/main/java/io/codelex/classesandobjects/practice/BankAccount.java
> <https://github.com/Verkqis/Homework/pull/4#discussion_r1226616330>:
>
> >  public class BankAccount {
> +
> +    DecimalFormat df = new DecimalFormat("###,##0.00");
> +
> +    public static void main(String[] args) {
>
> Tas pats - iznes main metodi ārā citā klasē.
> ------------------------------
>
> In
> src/main/java/io/codelex/classesandobjects/practice/savingsaccount/SavingsAccountTest.java
> <https://github.com/Verkqis/Homework/pull/4#discussion_r1226617887>:
>
> > +
> +import java.math.BigDecimal;
> +import java.util.Scanner;
> +
> +public class SavingsAccountTest {
> +
> +
> +    public static void main(String[] args) {
> +
> +        Scanner sc = new Scanner(System.in);
> +        BigDecimal input = new BigDecimal(0);
> +
> +        System.out.print("How much money is in the account?: ");
> +        input = sc.nextBigDecimal();
> +
> +        SavingsAccount JohnDoe = new SavingsAccount(input);
>
> Mainīgo vajadzētu ar mazo burtu, savādāk liekas, ka šeit, piemēram, tiek
> saukta statiska metode no klases nevis parasta no objekta -
> JohnDoe.setAnnualInterest(input);
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Verkqis/Homework/pull/4#pullrequestreview-1474849367>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6QBZLXZQDGAWDWIY7E3JC3XK4GA5ANCNFSM6AAAAAAYH4N6UY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-02 05:05 UTC, janistumpelis approved these changes

2023-07-02 06:58 UTC, merged